# This is a config for E2B sandbox template.
# You can use template ID (hb5oc45lzy0v9eh0y9ut) or template name (litellm-4gb) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("litellm-4gb") # Sync sandbox
# sandbox = await AsyncSandbox.create("litellm-4gb") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('litellm-4gb')

memory_mb = 4_096
cpu_count = 8
ready_cmd = "pg_isready -h localhost -p 5432 -U litellm"
start_cmd = "/usr/local/bin/start-db"
dockerfile = "e2b.Dockerfile"
template_name = "litellm-4gb"
template_id = "hb5oc45lzy0v9eh0y9ut"
